services:
  - type: web
    name: rommelaere-renov
    env: node
    plan: free
    region: frankfurt
    nodeVersion: 20
    buildCommand: |
      corepack enable
      pnpm install --frozen-lockfile
      pnpm run build
    startCommand: pnpm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: OAUTH_SERVER_URL
        sync: false
      - key: BUILT_IN_FORGE_API_URL
        sync: false
      - key: BUILT_IN_FORGE_API_KEY
        sync: false
      - key: OWNER_OPEN_ID
        sync: false
      - key: VITE_APP_ID
        sync: false
